### ISSUE TITLE
Invalid GPG key line

### ISSUE THREAD

**Issue by GreenCappuccino** [andyholmes/flatter#50]
when using `gpg2 --armor --export` I get:
```pem
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZFBwmxYJKwYBBAHaRw8BAQdAJ0ko9gnnrEgZRSdWGX7dZphnDwRRR0RHg/6N
M1RVAkO0GWdyZWVuY2FwcHVjY2lub0BnaXRodWIuaW+ImQQTFgoAQRYhBAaeTyTC
uH95D8qNLHmkIk+s2UxLBQJkUHCbAhsDBQkDwmcABQsJCAcCAiICBhUKCQgLAgQW
AgMBAh4HAheAAAoJEHmkIk+s2UxLiUkBAJDbCajFtv50P5GggAgwi8wDKkL/6z3I
hjsiqUaSd/u9AQDvYiA4+wGV4b0kgocykpN1UOfUPDLkG8UQWMSqW6UfAbg4BGRQ
cJsSCisGAQQBl1UBBQEBB0CdOQmSO1eXPN88mcvMrpWjpmvVFsTrRtnc7RUDDWpk
HAMBCAeIeAQYFgoAIBYhBAaeTyTCuH95D8qNLHmkIk+s2UxLBQJkUHCbAhsMAAoJ
EHmkIk+s2UxLrMYBAP3uXj1LIRnOJRsNyIMdn+VtTucxiR1TGcJ02gZcCsgAAP99
0uiw1QXW28zZJMIXk5y6tuWiSegwwzHVTdNZlPXQCg==
=xm4n
-----END PGP PUBLIC KEY BLOCK-----
```

There is an extra checksum line at the end.

When running the Github Action, Flatter generates the line:
`GPGKey=mDMEZFBwmxYJKwYBBAHaRw8BAQdAJ0ko9gnnrEgZRSdWGX7dZphnDwRRR0RHg/6NM1RVAkO0GWdyZWVuY2FwcHVjY2lub0BnaXRodWIuaW+ImQQTFgoAQRYhBAaeTyTCuH95D8qNLHmkIk+s2UxLBQJkUHCbAhsDBQkDwmcABQsJCAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEHmkIk+s2UxLiUkBAJDbCajFtv50P5GggAgwi8wDKkL/6z3IhjsiqUaSd/u9AQDvYiA4+wGV4b0kgocykpN1UOfUPDLkG8UQWMSqW6UfAbg4BGRQcJsSCisGAQQBl1UBBQEBB0CdOQmSO1eXPN88mcvMrpWjpmvVFsTrRtnc7RUDDWpkHAMBCAeIeAQYFgoAIBYhBAaeTyTCuH95D8qNLHmkIk+s2UxLBQJkUHCbAhsMAAoJEHmkIk+s2UxLrMYBAP3uXj1LIRnOJRsNyIMdn+VtTucxiR1TGcJ02gZcCsgAAP990uiw1QXW28zZJMIXk5y6tuWiSegwwzHVTdNZlPXQCg===xm4n`

Importing with the `flatpak` command, it thinks that this is invalid:
`error: Error modifying remote: GPG: Unable to export keys: GPGME: No data`
As a consequence, the generated `index.flatpakrepo` file does not work.

The solution is to remove the checksum at the end of the `GPGKey` line. This works:
`GPGKey=mDMEZFBwmxYJKwYBBAHaRw8BAQdAJ0ko9gnnrEgZRSdWGX7dZphnDwRRR0RHg/6NM1RVAkO0GWdyZWVuY2FwcHVjY2lub0BnaXRodWIuaW+ImQQTFgoAQRYhBAaeTyTCuH95D8qNLHmkIk+s2UxLBQJkUHCbAhsDBQkDwmcABQsJCAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEHmkIk+s2UxLiUkBAJDbCajFtv50P5GggAgwi8wDKkL/6z3IhjsiqUaSd/u9AQDvYiA4+wGV4b0kgocykpN1UOfUPDLkG8UQWMSqW6UfAbg4BGRQcJsSCisGAQQBl1UBBQEBB0CdOQmSO1eXPN88mcvMrpWjpmvVFsTrRtnc7RUDDWpkHAMBCAeIeAQYFgoAIBYhBAaeTyTCuH95D8qNLHmkIk+s2UxLBQJkUHCbAhsMAAoJEHmkIk+s2UxLrMYBAP3uXj1LIRnOJRsNyIMdn+VtTucxiR1TGcJ02gZcCsgAAP990uiw1QXW28zZJMIXk5y6tuWiSegwwzHVTdNZlPXQCg==`

Do you have any insight as to how this worked before, and why the repo import isn't working on my system right now? Much appreciated.

**Comment by andyholmes** [comment]
I have no idea, to be honest I wasn't sure this was a bug in flatter 🙂 I've seen the same problem but thought it was on the GPG side.
