### ISSUE TITLE
Support AppStream data

### ISSUE THREAD

**Issue by mserajnik** [andyholmes/flatter#71]
Hey, first of all thanks for this project; I use it to deploy [a repository](https://flatpak.mser.at/) and it's been working flawlessly so far.

One thing that seems to be missing is support for AppStream data provided via [AppData files](https://docs.flatpak.org/en/latest/conventions.html#appdata-files).

I don't have that much experience with Flatpak yet, but from what I understand, it's not only used for GUI Flatpak managers to have some more information to display, but also to show the application version when an application is listed in the Flatpak CLI (from the `<releases>` section in the AppData file) as well as when searching via `flatpak search` (among probably some other use cases).

I am exposing such AppData files in my manifests (e.g., [here](https://github.com/mserajnik/flatpak.mser.at/blob/master/apps/com.github.silquirk.SilQ/com.github.silquirk.SilQ.yaml#L66)) in the same way as I've seen in Flathub repositories (e.g., [here](https://github.com/flathub/com.shatteredpixel.shatteredpixeldungeon/blob/master/com.shatteredpixel.shatteredpixeldungeon.yaml#L35)) but it's seemingly not used/working.

When I run `flatpak update --appstream <my repository name>` I also get an error:

```sh
flatpak remote-add --if-not-exists flatpak.mser.at https://flatpak.mser.at/index.flatpakrepo
flatpak update --appstream flatpak.mser.at
error: Error updating appstream2: No such ref 'appstream2/aarch64' in remote flatpak.mser.at; Error updating appstream: No such ref 'appstream/aarch64' in remote flatpak.mser.at
```

I get the same error when adding your example repository, so I assume it's not just a mistake on my end:

```sh
flatpak remote-add --if-not-exists flatter https://flatter.andyholmes.ca/index.flatpakrepo
flatpak update --appstream flatter
error: Error updating appstream2: No such ref 'appstream2/aarch64' in remote flatter; Error updating appstream: No such ref 'appstream/aarch64' in remote flatter
```

Note that this was run from an aarch64 VM (to test the applications), but I do get the same error on x86_64 (it just says `appstream/x86_64` instead of `appstream/aarch64` then).

Am I missing something or is this just not supported right now? If the latter, are there any plans to add this? Sadly, I can't find much specific information about how this is supposed to work, except for [this article](https://blogs.gnome.org/alexl/2017/02/10/maintaining-a-flatpak-repository/) which states the following on the matter:

> AppStream branches
>
> In order to support nice graphical frontends like gnome-software, flatpak uses a metadata format called [AppStream](https://www.freedesktop.org/wiki/Distributions/AppStream/). The way this works is that each application ships an AppData xml file, and an icon. Then when you run flatpak build-update-repo, each such xml file and icon are extracted and put in a separate per-arch appdata branch (called e.g. appstream/x86_64). Flatpak then mirrors this branch locally for each remote, and this data is used by gnome-software.
>
> So, make sure your application ships an appdata file, and make sure you run build-update-repo to update the branches whenever an application changes.

Thank you!

**Comment by andyholmes** [comment]
Hi, I don't really know how this is supposed to work, but I would accept a patch if you can get it work.

I guess in principle it sounds like running `flatpak build-update-repo` should set it up automatically? Maybe try adding a function similar to this:

https://github.com/andyholmes/flatter/blob/f16e09ad6c31fdba5de0a3a0f238a096fe41f6b7/src/flatter.js#L217-L251

Then call it from `main.js`, right before `await flatter.saveCache()`:

https://github.com/andyholmes/flatter/blob/f16e09ad6c31fdba5de0a3a0f238a096fe41f6b7/src/main.js#L54-L70

Should be easy enough to test this locally.

**Comment by mserajnik** [comment]
Thanks, I'll give this a try and report back with any findings.
