### ISSUE TITLE
TypeError: artifact.create is not a function

### ISSUE THREAD

**Issue by philn** [andyholmes/flatter#82]
Hi :)

My glide nightly flatter failed last night, maybe a regression from yesterday?

https://github.com/philn/glide/actions/runs/7923949191/job/21634675468

**Comment by philn** [comment]
Backtrace:

```
 file:///__w/_actions/andyholmes/flatter/main/dist/index.js:137139
          const artifactClient = artifact.create();
                                          ^
  
  TypeError: artifact.create is not a function
      at run (file:///__w/_actions/andyholmes/flatter/main/dist/index.js:137139:41)
```

**Comment by philn** [comment]
@andyholmes Is this working in your projects?

**Comment by andyholmes** [comment]
Hey sorry, I saw this yesterday, but busy and Friday :sweat_smile:

I've got a fix up, I think it was a simple as a constructor change.

AFAIK you shouldn't have to wait for the containers to build, it just runs the JS straight out of the repo, so let me know!

**Comment by philn** [comment]
Thanks!

**Comment by philn** [comment]
I confirm it's fixed, thanks again :)
